### ISSUE TITLE
Bug in Multi-Process Backend

### ISSUE THREAD

**Issue by heikomuller** [VizierDB/web-api-async#1]
2019-02-28 12:39:05,850] ERROR in server: semaphore or lock released too many times
127.0.0.1 - - [28/Feb/2019 12:39:05] "POST /vizier-db/api/v1/projects/90315ace/branches/a2e697cb/head HTTP/1.1" 400 -
Error on request:
Traceback (most recent call last):
  File "/home/heiko/software/anaconda2/envs/vizasync/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/heiko/software/anaconda2/envs/vizasync/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/home/heiko/software/anaconda2/envs/vizasync/lib/python2.7/site-packages/werkzeug/serving.py", line 224, in write
    self.send_response(code, msg)
  File "/home/heiko/software/anaconda2/envs/vizasync/lib/python2.7/site-packages/werkzeug/serving.py", line 337, in send_response
    self.wfile.write(hdr.encode('ascii'))
IOError: [Errno 32] Broken pipe

**Comment by okennedy** [comment]
Can't reproduce
