### ISSUE TITLE
ds.update_dataset is not implemented

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-api-async#3]

**Comment by okennedy** [comment]
When calling `vizierdb.update_dataset` in a python cell: 

```
NotImplementedError:(): Traceback (most recent call last):
  File "/home/vizier/web-api-async/vizier/engine/packages/pycell/processor.py", line 97, in execute_script
    exec source in variables, variables
  File "<string>", line 6, in <module>
  File "/home/vizier/web-api-async/vizier/engine/packages/pycell/client/base.py", line 291, in update_dataset
    row_counter = source_dataset.max_row_id() + 1
  File "/home/vizier/web-api-async/vizier/datastore/dataset.py", line 247, in max_row_id
    raise NotImplementedError
NotImplementedError
```
