### ISSUE TITLE
Error connecting to s3a links

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-api-async#32]
```
AttributeError:("'MimirDatastore' object has no attribute 'download_dataset'",): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/vizier/engine/backend/base.py", line 280, in exec_command
    context=context
  File "/usr/local/lib/python2.7/dist-packages/vizier/engine/packages/vizual/processor.py", line 102, in compute
    context=context
  File "/usr/local/lib/python2.7/dist-packages/vizier/engine/packages/vizual/processor.py", line 432, in compute_load_dataset
    human_readable_name = ds_name.upper()
  File "/usr/local/lib/python2.7/dist-packages/vizier/engine/packages/vizual/api/fs.py", line 341, in load_dataset
    dataset = datastore.download_dataset(
AttributeError: 'MimirDatastore' object has no attribute 'download_dataset'
```

**Comment by okennedy** [comment]
fixed in 4c0b0406ffd345ab8069736bc2b836aacb8f3075
