### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst' during pip install

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-api-async#43]
```
okennedy@loki:~/Documents/web-api-async$ pip3 install --upgrade --no-cache vizier
Collecting vizier
  Downloading https://files.pythonhosted.org/packages/0e/7a/cf2078af618cabcce4410e6d682c329122d24c68be9ac66114f3ca11c4e0/vizier-0.1dev.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/okennedy/.pyenv/versions/3.7.4/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hv7iasuu/vizier/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hv7iasuu/vizier/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-hv7iasuu/vizier/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hv7iasuu/vizier/setup.py", line 13, in <module>
        long_description=open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by okennedy** [comment]
Wrong Vizier >.<
