### ISSUE TITLE
TypeError during notebook export

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-api-async#44]
```
TypeError

TypeError: string argument expected, got 'bytes'
Traceback (most recent call last)

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app

    response = self.handle_exception(e)

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/home/okennedy/.local/lib/python3.7/site-packages/vizier/api/webservice/server.py", line 136, in export_project

    with tarfile.open(fileobj=si, mode="w:gz") as tar:

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/tarfile.py", line 1591, in open

    return func(name, filemode, fileobj, **kwargs)

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/tarfile.py", line 1638, in gzopen

    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/gzip.py", line 194, in __init__

    self._write_gzip_header()

    File "/home/okennedy/.pyenv/versions/3.7.4/lib/python3.7/gzip.py", line 222, in _write_gzip_header

    self.fileobj.write(b'\037\213')             # magic header

    TypeError: string argument expected, got 'bytes'

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

```

**Comment by mrb24** [comment]
closed by commit: 7e845bbb45c8700b661e648fe534f5daf7970b31
